version: "3"

services:
  relay:
    build: .
    restart: always
    env_file:
      - .env

  mqtt:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto_config:/mosquitto/config"