version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto_config:/mosquitto/config"

  relay:
    image: ghcr.io/agridata-trade/robonomics-relay:main
    restart: always
    volumes:
      - ./config.json:/app/config.json
    env_file:
      - .env
    depends_on:
      - mqtt